title: Azure
resources:
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /local/tracker-card.js?v=0.3.2
    type: js
  - url: /local/card-tools.js?v=f5bb8e
    type: js
  - url: /local/auto-entities.js?v=f9a58c
    type: js

views:
  - title: Overview
    icon: mdi:home-assistant
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: Overview
        filter:
          include:
            - group.alex
            - group.irina
            - group.creekview
            - group.sway
            - group.cars
            - group.keys
  - title: Creekview
    panel: true
    cards:
      - type: iframe
        url: 'https://cv-hassio.karel.in/lovelace/iframe?kiosk&show_tabs'
        aspect_ratio: 300%
  - title: Sway
    icon: mdi:home-modern
    panel: true
    cards:
      - type: iframe
        url: 'https://sway-hassio.karel.in/lovelace/default_view?kiosk&show_tabs'
        aspect_ratio: 300%
  - title: System
    icon: mdi:wrench
    cards:
      - type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker 
