history:
logbook:
recorder:
  db_url: !secret mysql_connstring

owntracks:
  mqtt_topic: "owntracks/#"

homeassistant:
  customize_glob:
    "device_tracker.*_icloud_*":
      hidden: true

device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
  - platform: automatic
    client_id: !secret automatic_client_id_mb
    secret: !secret automatic_secret_mb
    devices:
      - 2014 Mercedes-Benz GL-Class
  # - platform: automatic
  #   client_id: !secret automatic_client_id_bmw
  #   secret: !secret automatic_secret_bmw
    
  # - platform: google_maps
  #   username: !secret google_username
  #   password: !secret google_password
    
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
#    site_id: !secret unifi_siteid
    interval_seconds: 12
    consider_home: 900
    ssid_filter:
      - 'Creekview'
      - 'Broadway'
    new_device_defaults:
      track_new_devices: no
      hide_if_away: True
  # - platform: mqtt
  #   devices:
  #     alex_creekview_mqtt: 'houses/cv/people/alex'
  #     alex_sway_mqtt: 'houses/sway/people/alex'
  #     irina_creekview_mqtt: 'houses/cv/people/irina'
  #     irina_sway_mqtt: 'houses/sway/people/irina'

# binary_sensor:
#   - platform: bayesian
#     prior: 0.5
#     name: 'Alex Creekview'
#     device_class: presence
#     probability_threshold: 0.9
#     observations:
#       - entity_id: 'device_tracker.alexiphonexsm'
#         prob_given_true: 0.9
#         prob_given_false: 0.2
#         platform: 'state'
#         to_state: 'creekview'
#       - entity_id: 'device_tracker.ak_alexiphonexsm'
#         prob_given_true: 0.9
#         prob_given_false: 0.2
#         platform: 'state'
#         to_state: 'creekview'
#       - entity_id: 'device_tracker.alexiphonexsm'
#         prob_given_true: 0.1
#         platform: 'state'
#         to_state: 'santa_monica'
      # - entity_id: 'device_tracker.alex_creekview_mqtt'
      #   prob_given_true: 0.9
      #   prob_given_false: 0.2
      #   platform: 'state'
      #   to_state: 'home'
  # - platform: bayesian
  #   prior: 0.3
  #   name: 'Alex Sway'
  #   device_class: presence
  #   probability_threshold: 0.9
  #   observations:
  #     - entity_id: 'device_tracker.ak_alexiphonexsm'
  #       prob_given_true: 0.9
  #       prob_given_false: 0.2
  #       platform: 'state'
  #       to_state: 'sway'
  #     - entity_id: 'device_tracker.alexiphonexsm'
  #       prob_given_true: 0.7
  #       prob_given_false: 0.2
  #       platform: 'state'
  #       to_state: 'santa_monica'
  #     - entity_id: 'device_tracker.alexiphonexsm'
  #       prob_given_true: 0.1
  #       platform: 'state'
  #       to_state: 'valley'
      # - entity_id: 'device_tracker.alex_creekview_mqtt'
      #   prob_given_true: 0.9
      #   prob_given_false: 0.2
      #   platform: 'state'
      #   to_state: 'away'
      # - entity_id: 'device_tracker.alex_sway_mqtt'
      #   prob_given_true: 0.9
      #   prob_given_false: 0.2
      #   platform: 'state'
      #   to_state: 'home'

# sensor:
#   - platform: template
#     sensors:
#       alex_location:
#         friendly_name: Alex
#         value_template: >-
#           {% if is_state('binary_sensor.alex_creekview','on') %}
#             Creekview
#           {% elif is_state('binary_sensor.alex_sway','on') %}
#             Sway
#           {% else %}
#             Away
#           {% endif %}
        
# automation:
#   - alias: "Alex Bayesian"
#     trigger:
#       - platform: state
#         entity_id: sensor.alex_location
#         to: 'Creekview'
#       - platform: state
#         entity_id: binary_sensor.alex_creekview
#         to: 'on'
#     action:
#       - service: mqtt.publish
#         data_template:
#           topic: "houses/cv/people/alex"        
#           payload: "on"
#       - service: mqtt.publish
#         data_template:
#           topic: "houses/sway/people/alex"
#           payload: "off"
        
#  - platform: automatic
#    client_id: !secret automatic_client_id
#    secret: !secret automatic_secret
# - platform: automatic
#    client_id: !secret automatic_client_id_old
#    secret: !secret automatic_secret_old
    
#  - platform: trackr
#    username: !secret trackr_username
#    password: !secret trackr_password 

    
