ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: true

nuheat:
  username: !secret nuheat_username
  password: !secret nuheat_password
  devices: 255666

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

homeassistant:
  customize_glob:
    "sensor.*_humidity":
      hidden: true
    "sensor.*_temperature":
      hidden: true
    "weather.*":
      hidden: true
    "binary_sensor.*_occupancy":
      hidden: true

# group:
#   hvac_cv:
#     name: CV HVAC
#     view: false
#     hidden: true
#     entities:
#       - climate.alex_office
#       - climate.downstairs
#       - climate.guest_bedroom
#       - climate.living_room
#       - climate.master_bedroom
#       - climate.ts_mb_floors
#       - climate.upstairs

# script:
#   hvac_cv_off:
#     sequence:
#       service: climate.turn_off
#       data: 
#         entity_id: group.hvac_cv
