weather:
  - platform: darksky
    name: Sway
    api_key: !secret darksky_api_key
    latitude: !secret sway_la
    longitude: !secret sway_lo

homeassistant:
  customize:
    weather.sway:
      hidden: false