device_tracker:
  - platform: automatic
    client_id: !secret automatic_client_id_mb
    secret: !secret automatic_secret_mb
    devices:
      - '2014 Mercedes-Benz GL-Class'
#      - C_9298CBA3F6235244
  - platform: automatic
    client_id: !secret automatic_client_id_bmw
    secret: !secret automatic_secret_bmw
    devices:
      - '2011 BMW Z4'
#      - C_3712472641DA16CC

group:
  cars:
    name: Cars
    icon: mdi:car
    entities:
      - device_tracker.car_mb
      - sensor.car_mb_fuel
      - device_tracker.tile_3b3f0bd54db6e25d
      - device_tracker.car_bmw
#      - sensor.car_bmw_fuel
      - device_tracker.tile_1520116806d5c3c0
  # cars_ui:
  #   name: Cars
  #   icon: mdi:car
  #   entities:
  #     - group.cars

homeassistant:
  customize:
    device_tracker.car_bmw:
      picture: /local/bmw_z4.png
      icon: mdi:car-convertible
      name: BMW Z4
    device_tracker.car_mb:
      picture: /local/2014_mercedesbenz_glclass.jpg
      icon: mdi:car-estate
      name: Mercedes-Benz GL-Class

sensor:
  - platform: template
    sensors:
      car_mb_fuel:
        friendly_name: MB Fuel
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.car_mb.attributes.fuel_level|round }}
        icon_template: >-
          {% if states.device_tracker.car_mb.attributes.fuel_level > 80 %}
            mdi:gauge-full
          {% elif states.device_tracker.car_mb.attributes.fuel_level > 40 %}
            mdi:gauge
          {% elif states.device_tracker.car_mb.attributes.fuel_level > 25 %}
            mdi:gauge-low
          {% else %}
            mdi:gauge-empty
          {% endif %}
  # - platform: template
  #   sensors:
  #     car_bmw_fuel:
  #       friendly_name: BMW Fuel
  #       unit_of_measurement: '%'
  #       value_template: >-
  #         {{ states.device_tracker.car_bmw.attributes.fuel_level|round }}
  #       icon_template: >-
  #         {% if states.device_tracker.car_bmw.attributes.fuel_level > 80 %}
  #           mdi:gauge-full
  #         {% elif states.device_tracker.car_bmw.attributes.fuel_level > 40 %}
  #           mdi:gauge
  #         {% elif states.device_tracker.car_bmw.attributes.fuel_level > 25 %}
  #           mdi:gauge-low
  #         {% else %}
  #           mdi:gauge-empty
  #         {% endif %}
