homeassistant:
  customize:
    group.galina:
      hidden: true

group:
  galina:
    name: Galina
    icon: mdi:face
    entities:
      - device_tracker.galina
      - device_tracker.galina_iphone
      - device_tracker.galina_watch
      - device_tracker.galina_ipad
# galina_ui:
  #   name: Galina
  #   icon: mdi:face
  #   view: true
  #   entities:
  #     - group.galina