weather:
  - platform: darksky
    name: Creekview
    api_key: !secret darksky_api_key
    latitude: !secret creekview_la
    longitude: !secret creekview_lo

homeassistant:
  customize:
    weather.creekview:
      hidden: false
    climate.master_bathroom:
      icon: mdi:gradient
  customize_glob:
    "sensor.*_humidity":
      hidden: true
    "sensor.*_temperature":
      hidden: true
    "weather.*":
      hidden: true
    "binary_sensor.*_occupancy":
      hidden: true

nuheat:
  username: !secret nuheat_username
  password: !secret nuheat_password
  devices: 255666

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

ecobee:
  api_key: !secret ecobee_api_key_azure

script:
  cv_hvac_away:
    sequence: 
      - service: climate.ecobee_resume_program
        data:
          entity_id:
            - climate.downstairs
            - climate.guest_bedroom
            - climate.master_bedroom
            - climate.upstairs
            - climate.living_room
      - service: climate.nuheat_resume_program
        data:
          entity_id:
            - climate.master_bathroom
      - service: climate.set_operation_mode
        data:
          entity_id:
            - climate.downstairs
            - climate.guest_bedroom
            - climate.master_bedroom
            - climate.upstairs
            - climate.living_room
          operation_mode: 'off'
      - service: climate.set_temperature
        data:
          entity_id: climate.master_bathroom
          temperature: 5
      - service: climate.set_hold_mode
        data:
          entity_id: climate.master_bathroom
          hold_mode: temperature
  cv_hvac_away_alex:
    sequence:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.alex_office
          operation_mode: 'off'
#  cv_hvac_home_summer:
  cv_hvac_home_winter:
    sequence:
      - service: climate.ecobee_resume_program
        data:
          entity_id:
            - climate.alex_office
            - climate.downstairs
            - climate.guest_bedroom
            - climate.master_bedroom
            - climate.master_bathroom
            - climate.upstairs
            - climate.living_room
      - service: climate.set_temperature
        data:
          entity_id: climate.master_bathroom
          temperature: 30
      - service: climate.set_hold_mode
        data:
          entity_id: climate.master_bathroom
          hold_mode: temperature
      - delay:
          seconds: 30
      - service: climate.set_operation_mode
        data:
          entity_id:
            - climate.downstairs
            - climate.guest_bedroom
            - climate.master_bedroom
            - climate.master_bathroom
          operation_mode: 'heat'
  cv_hvac_home_winter_alex:
    sequence:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.alex_office
      - service: climate.set_operation_mode
        data:
          entity_id: climate.alex_office
          operation_mode: 'heat'

# group:
#   creekview_hvac:
#     name: Creekview HVAC
#     view: false
#     control: hidden
#     entities:
#       - weather.creekview
#       - script.cv_hvac_away
#       - script.cv_hvac_home_winter
#       - climate.downstairs
#       - climate.master_bedroom
#       - climate.master_bathroom
#       - climate.alex_office
#   creekview_hvac_misc:
#     name: Creekview HVAC Misc
#     view: false
#     control: hidden
#     entities:
#       - climate.alex_office_aux
#       - climate.gym
#       - climate.guest_bedroom
#       - climate.living_room
#       - climate.upstairs

